# Generated by Django 6.0.5 on 2026-08-22 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, max_digits=14)),
                ('existing_debt', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monthly_debt_payment', models.DecimalField(decimal_places=2, max_digits=14)),
                ('savings_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('credit_score', models.PositiveIntegerField()),
                ('previous_loans', models.PositiveIntegerField(default=0)),
                ('loans_repaid', models.PositiveIntegerField(default=0)),
                ('loans_defaulted', models.PositiveIntegerField(default=0)),
                ('late_payments', models.PositiveIntegerField(default=0)),
                ('credit_history_years', models.PositiveIntegerField(default=0)),
                ('requested_loan_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('loan_term_months', models.PositiveIntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, default=15, max_digits=6)),
                ('employment_years', models.PositiveIntegerField(default=0)),
                ('collateral_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('employment_type', models.CharField(default='Salaried', max_length=80)),
                ('education', models.CharField(default='Graduate', max_length=80)),
                ('loan_purpose', models.CharField(default='Personal', max_length=100)),
                ('loan_type', models.CharField(default='Personal', max_length=80)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('risk_score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('ai_recommendation', models.CharField(choices=[('APPROVED', 'Approved'), ('REVIEW', 'Review'), ('REJECTED', 'Rejected')], max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('explanation', models.TextField()),
                ('probabilities', models.JSONField(default=dict)),
                ('important_factors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
